// <auto-generated>
//   This file is replaced by the .NET build unit at generation time: the unit
//   materializes obj/BakedProfile.g.cs into the per-build source tree with the
//   baked profile embedded as the Json constant (architecture.md Sec 5.1).
//   This checked-in stub lets the implant compile and run on its own (dev runs)
//   with an empty baked profile -- flag/env drive everything then.
// </auto-generated>
namespace Rod.Implant;

internal static class BakedProfile
{
    public const string Json = "";
}
