<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="Grpc.Core.Api" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="protos/rod.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
