// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rod.Persistence;

#nullable disable

namespace Rod.Persistence.Migrations
{
    [DbContext(typeof(RodPersistenceDbContext))]
    partial class RodPersistenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rod.Audit.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("ArtifactId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_artifacts_engagement_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_artifacts_task_id");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("Rod.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<long>("AppendSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("append_sequence");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verb");

                    b.HasKey("EventId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_audit_events_engagement_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Engagements.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Implants.Implant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<int>("Class")
                        .HasColumnType("integer")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeployedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deployed_by");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("KillDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kill_date");

                    b.Property<Guid?>("ParentImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_implant_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_implants_engagement_id");

                    b.ToTable("implants", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Operators.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.HasKey("Id");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_sessions_engagement_id");

                    b.HasIndex("ImplantId")
                        .HasDatabaseName("ix_sessions_implant_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verb");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_tasks_engagement_id");

                    b.HasIndex("ImplantId")
                        .HasDatabaseName("ix_tasks_implant_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredStagerToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("stager_token_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<int>("RemainingUses")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_uses");

                    b.HasKey("Id");

                    b.ToTable("stager_tokens", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Engagements.Engagement", b =>
                {
                    b.OwnsMany("Rod.CoreState.Engagements.EngagementMembership", "Members", b1 =>
                        {
                            b1.Property<Guid>("EngagementId")
                                .HasColumnType("uuid")
                                .HasColumnName("engagement_id");

                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("operator_id");

                            b1.Property<DateTimeOffset>("AddedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("added_at");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("EngagementId", "OperatorId");

                            b1.ToTable("engagement_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EngagementId");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
