// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rod.proto

package rodpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enrollment outcome, mapped from the stager-token redeem result
// (architecture.md Sec.9). The transport endpoint maps each redeem failure to a
// distinct status so an implant gets an actionable reason, not just "no".
type EnrollStatus int32

const (
	EnrollStatus_ENROLL_STATUS_UNSPECIFIED EnrollStatus = 0
	EnrollStatus_ENROLL_STATUS_OK          EnrollStatus = 1
	EnrollStatus_ENROLL_STATUS_BAD_TOKEN   EnrollStatus = 2
	EnrollStatus_ENROLL_STATUS_EXPIRED     EnrollStatus = 3
	EnrollStatus_ENROLL_STATUS_SPENT       EnrollStatus = 4
)

// Enum value maps for EnrollStatus.
var (
	EnrollStatus_name = map[int32]string{
		0: "ENROLL_STATUS_UNSPECIFIED",
		1: "ENROLL_STATUS_OK",
		2: "ENROLL_STATUS_BAD_TOKEN",
		3: "ENROLL_STATUS_EXPIRED",
		4: "ENROLL_STATUS_SPENT",
	}
	EnrollStatus_value = map[string]int32{
		"ENROLL_STATUS_UNSPECIFIED": 0,
		"ENROLL_STATUS_OK":          1,
		"ENROLL_STATUS_BAD_TOKEN":   2,
		"ENROLL_STATUS_EXPIRED":     3,
		"ENROLL_STATUS_SPENT":       4,
	}
)

func (x EnrollStatus) Enum() *EnrollStatus {
	p := new(EnrollStatus)
	*p = x
	return p
}

func (x EnrollStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rod_proto_enumTypes[0].Descriptor()
}

func (EnrollStatus) Type() protoreflect.EnumType {
	return &file_rod_proto_enumTypes[0]
}

func (x EnrollStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollStatus.Descriptor instead.
func (EnrollStatus) EnumDescriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{0}
}

// Outcome of the handshake. OK means presence is recorded and the stream is
// live; anything else closes the stream.
type HandshakeStatus int32

const (
	HandshakeStatus_HANDSHAKE_STATUS_UNSPECIFIED       HandshakeStatus = 0
	HandshakeStatus_HANDSHAKE_STATUS_OK                HandshakeStatus = 1
	HandshakeStatus_HANDSHAKE_STATUS_VERSION_MISMATCH  HandshakeStatus = 2
	HandshakeStatus_HANDSHAKE_STATUS_UNKNOWN_IMPLANT   HandshakeStatus = 3
	HandshakeStatus_HANDSHAKE_STATUS_IDENTITY_MISMATCH HandshakeStatus = 4
	// The implant's baked-in kill date has passed (architecture.md Sec 7). The
	// teamserver refuses to open a session for an implant past its kill date;
	// the stream closes and the implant is expected to self-terminate.
	HandshakeStatus_HANDSHAKE_STATUS_KILL_DATE_EXPIRED HandshakeStatus = 5
)

// Enum value maps for HandshakeStatus.
var (
	HandshakeStatus_name = map[int32]string{
		0: "HANDSHAKE_STATUS_UNSPECIFIED",
		1: "HANDSHAKE_STATUS_OK",
		2: "HANDSHAKE_STATUS_VERSION_MISMATCH",
		3: "HANDSHAKE_STATUS_UNKNOWN_IMPLANT",
		4: "HANDSHAKE_STATUS_IDENTITY_MISMATCH",
		5: "HANDSHAKE_STATUS_KILL_DATE_EXPIRED",
	}
	HandshakeStatus_value = map[string]int32{
		"HANDSHAKE_STATUS_UNSPECIFIED":       0,
		"HANDSHAKE_STATUS_OK":                1,
		"HANDSHAKE_STATUS_VERSION_MISMATCH":  2,
		"HANDSHAKE_STATUS_UNKNOWN_IMPLANT":   3,
		"HANDSHAKE_STATUS_IDENTITY_MISMATCH": 4,
		"HANDSHAKE_STATUS_KILL_DATE_EXPIRED": 5,
	}
)

func (x HandshakeStatus) Enum() *HandshakeStatus {
	p := new(HandshakeStatus)
	*p = x
	return p
}

func (x HandshakeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandshakeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rod_proto_enumTypes[1].Descriptor()
}

func (HandshakeStatus) Type() protoreflect.EnumType {
	return &file_rod_proto_enumTypes[1]
}

func (x HandshakeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandshakeStatus.Descriptor instead.
func (HandshakeStatus) EnumDescriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{1}
}

// How a task turned out, as reported by the implant.
type TaskOutcome int32

const (
	TaskOutcome_TASK_OUTCOME_UNSPECIFIED TaskOutcome = 0
	TaskOutcome_TASK_OUTCOME_SUCCEEDED   TaskOutcome = 1
	TaskOutcome_TASK_OUTCOME_FAILED      TaskOutcome = 2
)

// Enum value maps for TaskOutcome.
var (
	TaskOutcome_name = map[int32]string{
		0: "TASK_OUTCOME_UNSPECIFIED",
		1: "TASK_OUTCOME_SUCCEEDED",
		2: "TASK_OUTCOME_FAILED",
	}
	TaskOutcome_value = map[string]int32{
		"TASK_OUTCOME_UNSPECIFIED": 0,
		"TASK_OUTCOME_SUCCEEDED":   1,
		"TASK_OUTCOME_FAILED":      2,
	}
)

func (x TaskOutcome) Enum() *TaskOutcome {
	p := new(TaskOutcome)
	*p = x
	return p
}

func (x TaskOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_rod_proto_enumTypes[2].Descriptor()
}

func (TaskOutcome) Type() protoreflect.EnumType {
	return &file_rod_proto_enumTypes[2]
}

func (x TaskOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskOutcome.Descriptor instead.
func (TaskOutcome) EnumDescriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{2}
}

// Protocol version exchanged at handshake.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         int32                  `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         int32                  `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_rod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// Per-frame identity. Application-layer binding that complements mTLS -- an
// implant certificate binds (implant_id, engagement_id) (architecture.md Sec.9);
// the envelope carries the same identifiers so the server can route and audit
// without trusting the wire alone.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngagementId  string                 `protobuf:"bytes,1,opt,name=engagement_id,json=engagementId,proto3" json:"engagement_id,omitempty"`
	ImplantId     string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_rod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetEngagementId() string {
	if x != nil {
		return x.EngagementId
	}
	return ""
}

func (x *Envelope) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// The unit that crosses every transport. Payload is opaque: its inner shape is
// defined by later protocol messages (tasking, enrollment, results) introduced
// alongside the M1.x entities.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_rod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{2}
}

func (x *Frame) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// The enrollment response (roadmap M1.2). On OK, carries the newly issued
// implant id, its engagement, and the bound leaf certificate plus the CA chain
// the implant needs. On failure, the ids/cert fields are empty and only status
// is meaningful.
type EnrollResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          EnrollStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=rod.v1.EnrollStatus" json:"status,omitempty"`
	ImplantId       string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	EngagementId    string                 `protobuf:"bytes,3,opt,name=engagement_id,json=engagementId,proto3" json:"engagement_id,omitempty"`
	LeafCertificate []byte                 `protobuf:"bytes,4,opt,name=leaf_certificate,json=leafCertificate,proto3" json:"leaf_certificate,omitempty"`
	CaChain         [][]byte               `protobuf:"bytes,5,rep,name=ca_chain,json=caChain,proto3" json:"ca_chain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_rod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollResponse) GetStatus() EnrollStatus {
	if x != nil {
		return x.Status
	}
	return EnrollStatus_ENROLL_STATUS_UNSPECIFIED
}

func (x *EnrollResponse) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *EnrollResponse) GetEngagementId() string {
	if x != nil {
		return x.EngagementId
	}
	return ""
}

func (x *EnrollResponse) GetLeafCertificate() []byte {
	if x != nil {
		return x.LeafCertificate
	}
	return nil
}

func (x *EnrollResponse) GetCaChain() [][]byte {
	if x != nil {
		return x.CaChain
	}
	return nil
}

// The implant's advertisement: its protocol version, identity, and the
// capability verbs it can dispatch (architecture.md Sec 10). implant_id is
// echoed for routing/audit; the binding is authoritative via mTLS, not the wire
// (architecture.md Sec 9).
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *ProtocolVersion       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ImplantId     string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_rod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeRequest) GetVersion() *ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *HandshakeRequest) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *HandshakeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// The server's handshake reply. version is the negotiated protocol version;
// engagement_id is echoed so the implant can confirm its bound engagement.
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HandshakeStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=rod.v1.HandshakeStatus" json:"status,omitempty"`
	Version       *ProtocolVersion       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	EngagementId  string                 `protobuf:"bytes,3,opt,name=engagement_id,json=engagementId,proto3" json:"engagement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_rod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeResponse) GetStatus() HandshakeStatus {
	if x != nil {
		return x.Status
	}
	return HandshakeStatus_HANDSHAKE_STATUS_UNSPECIFIED
}

func (x *HandshakeResponse) GetVersion() *ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *HandshakeResponse) GetEngagementId() string {
	if x != nil {
		return x.EngagementId
	}
	return ""
}

// A task handed to the implant: its id (echoed back on the result so the server
// can correlate), the capability verb, and its argument string.
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Verb          string                 `protobuf:"bytes,2,opt,name=verb,proto3" json:"verb,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_rod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *TaskRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// The implant's result for a task: the echoed task_id, the outcome, and the
// captured output (stdout/stderr or equivalent). Carried even on failure so the
// server captures the cause.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Outcome       TaskOutcome            `protobuf:"varint,2,opt,name=outcome,proto3,enum=rod.v1.TaskOutcome" json:"outcome,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_rod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_rod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_rod_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOutcome() TaskOutcome {
	if x != nil {
		return x.Outcome
	}
	return TaskOutcome_TASK_OUTCOME_UNSPECIFIED
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_rod_proto protoreflect.FileDescriptor

const file_rod_proto_rawDesc = "" +
	"\n" +
	"\trod.proto\x12\x06rod.v1\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x05R\x05minor\"j\n" +
	"\bEnvelope\x12#\n" +
	"\rengagement_id\x18\x01 \x01(\tR\fengagementId\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"O\n" +
	"\x05Frame\x12,\n" +
	"\benvelope\x18\x01 \x01(\v2\x10.rod.v1.EnvelopeR\benvelope\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xc8\x01\n" +
	"\x0eEnrollResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.rod.v1.EnrollStatusR\x06status\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x12#\n" +
	"\rengagement_id\x18\x03 \x01(\tR\fengagementId\x12)\n" +
	"\x10leaf_certificate\x18\x04 \x01(\fR\x0fleafCertificate\x12\x19\n" +
	"\bca_chain\x18\x05 \x03(\fR\acaChain\"\x88\x01\n" +
	"\x10HandshakeRequest\x121\n" +
	"\aversion\x18\x01 \x01(\v2\x17.rod.v1.ProtocolVersionR\aversion\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x9c\x01\n" +
	"\x11HandshakeResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.rod.v1.HandshakeStatusR\x06status\x121\n" +
	"\aversion\x18\x02 \x01(\v2\x17.rod.v1.ProtocolVersionR\aversion\x12#\n" +
	"\rengagement_id\x18\x03 \x01(\tR\fengagementId\"X\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04verb\x18\x02 \x01(\tR\x04verb\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"l\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x13.rod.v1.TaskOutcomeR\aoutcome\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output*\x94\x01\n" +
	"\fEnrollStatus\x12\x1d\n" +
	"\x19ENROLL_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENROLL_STATUS_OK\x10\x01\x12\x1b\n" +
	"\x17ENROLL_STATUS_BAD_TOKEN\x10\x02\x12\x19\n" +
	"\x15ENROLL_STATUS_EXPIRED\x10\x03\x12\x17\n" +
	"\x13ENROLL_STATUS_SPENT\x10\x04*\xe9\x01\n" +
	"\x0fHandshakeStatus\x12 \n" +
	"\x1cHANDSHAKE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HANDSHAKE_STATUS_OK\x10\x01\x12%\n" +
	"!HANDSHAKE_STATUS_VERSION_MISMATCH\x10\x02\x12$\n" +
	" HANDSHAKE_STATUS_UNKNOWN_IMPLANT\x10\x03\x12&\n" +
	"\"HANDSHAKE_STATUS_IDENTITY_MISMATCH\x10\x04\x12&\n" +
	"\"HANDSHAKE_STATUS_KILL_DATE_EXPIRED\x10\x05*`\n" +
	"\vTaskOutcome\x12\x1c\n" +
	"\x18TASK_OUTCOME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TASK_OUTCOME_SUCCEEDED\x10\x01\x12\x17\n" +
	"\x13TASK_OUTCOME_FAILED\x10\x0225\n" +
	"\x06Beacon\x12+\n" +
	"\aCheckIn\x12\r.rod.v1.Frame\x1a\r.rod.v1.Frame(\x010\x01B'Z%github.com/cw/rod/implant/rodpb;rodpbb\x06proto3"

var (
	file_rod_proto_rawDescOnce sync.Once
	file_rod_proto_rawDescData []byte
)

func file_rod_proto_rawDescGZIP() []byte {
	file_rod_proto_rawDescOnce.Do(func() {
		file_rod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rod_proto_rawDesc), len(file_rod_proto_rawDesc)))
	})
	return file_rod_proto_rawDescData
}

var file_rod_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rod_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rod_proto_goTypes = []any{
	(EnrollStatus)(0),         // 0: rod.v1.EnrollStatus
	(HandshakeStatus)(0),      // 1: rod.v1.HandshakeStatus
	(TaskOutcome)(0),          // 2: rod.v1.TaskOutcome
	(*ProtocolVersion)(nil),   // 3: rod.v1.ProtocolVersion
	(*Envelope)(nil),          // 4: rod.v1.Envelope
	(*Frame)(nil),             // 5: rod.v1.Frame
	(*EnrollResponse)(nil),    // 6: rod.v1.EnrollResponse
	(*HandshakeRequest)(nil),  // 7: rod.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 8: rod.v1.HandshakeResponse
	(*TaskRequest)(nil),       // 9: rod.v1.TaskRequest
	(*TaskResult)(nil),        // 10: rod.v1.TaskResult
}
var file_rod_proto_depIdxs = []int32{
	4, // 0: rod.v1.Frame.envelope:type_name -> rod.v1.Envelope
	0, // 1: rod.v1.EnrollResponse.status:type_name -> rod.v1.EnrollStatus
	3, // 2: rod.v1.HandshakeRequest.version:type_name -> rod.v1.ProtocolVersion
	1, // 3: rod.v1.HandshakeResponse.status:type_name -> rod.v1.HandshakeStatus
	3, // 4: rod.v1.HandshakeResponse.version:type_name -> rod.v1.ProtocolVersion
	2, // 5: rod.v1.TaskResult.outcome:type_name -> rod.v1.TaskOutcome
	5, // 6: rod.v1.Beacon.CheckIn:input_type -> rod.v1.Frame
	5, // 7: rod.v1.Beacon.CheckIn:output_type -> rod.v1.Frame
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rod_proto_init() }
func file_rod_proto_init() {
	if File_rod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rod_proto_rawDesc), len(file_rod_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rod_proto_goTypes,
		DependencyIndexes: file_rod_proto_depIdxs,
		EnumInfos:         file_rod_proto_enumTypes,
		MessageInfos:      file_rod_proto_msgTypes,
	}.Build()
	File_rod_proto = out.File
	file_rod_proto_goTypes = nil
	file_rod_proto_depIdxs = nil
}
