// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: rod.proto

package rodpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Beacon_CheckIn_FullMethodName = "/rod.v1.Beacon/CheckIn"
)

// BeaconClient is the client API for Beacon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Implant-initiated beacon channel (architecture.md Sec.5/8). The implant opens
// a long-lived reverse connection; the first exchange is the handshake, then
// the stream carries tasking and results in later milestones.
type BeaconClient interface {
	CheckIn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type beaconClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconClient(cc grpc.ClientConnInterface) BeaconClient {
	return &beaconClient{cc}
}

func (c *beaconClient) CheckIn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Beacon_ServiceDesc.Streams[0], Beacon_CheckIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Beacon_CheckInClient = grpc.BidiStreamingClient[Frame, Frame]

// BeaconServer is the server API for Beacon service.
// All implementations must embed UnimplementedBeaconServer
// for forward compatibility.
//
// Implant-initiated beacon channel (architecture.md Sec.5/8). The implant opens
// a long-lived reverse connection; the first exchange is the handshake, then
// the stream carries tasking and results in later milestones.
type BeaconServer interface {
	CheckIn(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedBeaconServer()
}

// UnimplementedBeaconServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBeaconServer struct{}

func (UnimplementedBeaconServer) CheckIn(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedBeaconServer) mustEmbedUnimplementedBeaconServer() {}
func (UnimplementedBeaconServer) testEmbeddedByValue()                {}

// UnsafeBeaconServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeaconServer will
// result in compilation errors.
type UnsafeBeaconServer interface {
	mustEmbedUnimplementedBeaconServer()
}

func RegisterBeaconServer(s grpc.ServiceRegistrar, srv BeaconServer) {
	// If the following call panics, it indicates UnimplementedBeaconServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Beacon_ServiceDesc, srv)
}

func _Beacon_CheckIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BeaconServer).CheckIn(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Beacon_CheckInServer = grpc.BidiStreamingServer[Frame, Frame]

// Beacon_ServiceDesc is the grpc.ServiceDesc for Beacon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Beacon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rod.v1.Beacon",
	HandlerType: (*BeaconServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckIn",
			Handler:       _Beacon_CheckIn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rod.proto",
}
