// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rod.Persistence;

#nullable disable

namespace Rod.Persistence.Migrations
{
    [DbContext(typeof(RodPersistenceDbContext))]
    [Migration("20261011015701_AddImplantCampaignAttribution")]
    partial class AddImplantCampaignAttribution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rod.Audit.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("ArtifactId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_artifacts_engagement_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_artifacts_task_id");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("Rod.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<long>("AppendSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("append_sequence");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verb");

                    b.HasKey("EventId");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_audit_events_engagement_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Engagements.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string>("Roe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roe");

                    b.HasKey("Id");

                    b.ToTable("engagements", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Implants.Implant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<string>("Arch")
                        .HasColumnType("text")
                        .HasColumnName("arch");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CampaignRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_recipient_id");

                    b.Property<string>("Carriers")
                        .HasColumnType("text")
                        .HasColumnName("carriers");

                    b.Property<int>("Class")
                        .HasColumnType("integer")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeployedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deployed_by");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid?>("EnrolledViaListenerId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_via_listener_id");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<double?>("JitterSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("jitter_seconds");

                    b.Property<DateTimeOffset?>("KillDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kill_date");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Os")
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.Property<Guid?>("ParentImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_implant_id");

                    b.Property<bool>("ReplayNonces")
                        .HasColumnType("boolean")
                        .HasColumnName("replay_nonces");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<double?>("SleepSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("sleep_seconds");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_implants_engagement_id");

                    b.ToTable("implants", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Launchers.Launcher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("launcher_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FrontEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front_endpoint");

                    b.Property<string>("FrontName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front_name");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_id");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<Guid>("PayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("payload_id");

                    b.Property<string>("PayloadOs")
                        .HasColumnType("text")
                        .HasColumnName("payload_os");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("TokenSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_secret");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_launchers_engagement_id");

                    b.ToTable("launchers", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Operators.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("handle");

                    b.HasKey("Id");

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<string>("LastCarrier")
                        .HasColumnType("text")
                        .HasColumnName("last_carrier");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_sessions_engagement_id");

                    b.HasIndex("ImplantId")
                        .HasDatabaseName("ix_sessions_implant_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.ShellSessions.ShellSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("shell_session_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset?>("LastInputAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_input_at");

                    b.Property<DateTimeOffset?>("LastOutputAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_output_at");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("Os")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("shell_sessions", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<long>("EnqueueSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("enqueue_seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EnqueueSequence"));

                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<long?>("StagedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("staged_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verb");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_tasks_engagement_id");

                    b.HasIndex("EnqueueSequence")
                        .HasDatabaseName("ix_tasks_enqueue_seq");

                    b.HasIndex("ImplantId")
                        .HasDatabaseName("ix_tasks_implant_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Rod.CoreState.WebShells.WebShellProfile", b =>
                {
                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<string>("AdapterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Decoder")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Encoder")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset?>("LastProbeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_probe_at");

                    b.Property<bool?>("LastProbeOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_probe_ok");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("RegisteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("ImplantId");

                    b.ToTable("webshell_profiles", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredAutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("automation_rule_id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<string>("CompletedVerb")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("completed_verb");

                    b.Property<int>("ConsecutiveRefusals")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_refusals");

                    b.Property<long>("CooldownSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("cooldown_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("EventKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_kind");

                    b.Property<int>("FireCount")
                        .HasColumnType("integer")
                        .HasColumnName("fire_count");

                    b.Property<long?>("IntervalSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("interval_seconds");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at");

                    b.Property<int>("MaxFirings")
                        .HasColumnType("integer")
                        .HasColumnName("max_firings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextFireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_fire_at");

                    b.Property<Guid?>("OnlyImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("only_implant_id");

                    b.Property<Guid>("TargetImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_implant_id");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_kind");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verb");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_automation_rules_enabled");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_automation_rules_engagement_id");

                    b.ToTable("automation_rules", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("body");

                    b.Property<bool>("BodyIsHtml")
                        .HasColumnType("boolean")
                        .HasColumnName("body_is_html");

                    b.Property<string>("BuildRequestJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("build_request_json");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("from_address");

                    b.Property<DateTimeOffset?>("LaunchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launched_at");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RelayHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relay_host");

                    b.Property<string>("RelayPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relay_password");

                    b.Property<int>("RelayPort")
                        .HasColumnType("integer")
                        .HasColumnName("relay_port");

                    b.Property<int>("RelayTls")
                        .HasColumnType("integer")
                        .HasColumnName("relay_tls");

                    b.Property<string>("RelayUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relay_username");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_campaigns_engagement_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_campaigns_state");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredCampaignRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_recipient_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EnrollTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("enroll_token_id");

                    b.Property<Guid?>("EnrolledImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_implant_id");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("Failure")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<string>("Name")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("PayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("payload_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("EnrollTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_campaign_recipients_enroll_token_id")
                        .HasFilter("enroll_token_id IS NOT NULL");

                    b.HasIndex("LureId")
                        .IsUnique()
                        .HasDatabaseName("ux_campaign_recipients_lure_id");

                    b.ToTable("campaign_recipients", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredDeployToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("deploy_token_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<int>("RemainingUses")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_uses");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ux_deploy_tokens_secret_hash");

                    b.ToTable("deploy_tokens", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredEngagementMembership", b =>
                {
                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("EngagementId", "OperatorId");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_engagement_members_operator_id");

                    b.ToTable("engagement_members", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredImplantTaskNonce", b =>
                {
                    b.Property<Guid>("ImplantId")
                        .HasColumnType("uuid")
                        .HasColumnName("implant_id");

                    b.Property<long>("NonceFloor")
                        .HasColumnType("bigint")
                        .HasColumnName("nonce_floor");

                    b.HasKey("ImplantId");

                    b.ToTable("implant_task_nonces", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredListenerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("listener_id");

                    b.Property<string>("BindAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bind_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PublicEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("public_endpoint");

                    b.Property<DateTimeOffset?>("RepointedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("repointed_at");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transport");

                    b.Property<string>("TrustPosture")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trust_posture");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_listener_definitions_engagement_id");

                    b.ToTable("listener_definitions", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredOperatorApiToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.HasKey("TokenId");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_api_tokens_hash");

                    b.HasIndex("OperatorId");

                    b.ToTable("operator_api_tokens", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredOperatorCredential", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OperatorId");

                    b.ToTable("operator_credentials", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredTaskSnippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("task_snippet_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps_json");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_task_snippets_engagement_id");

                    b.ToTable("task_snippets", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredWebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_subscription_id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_count");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.PrimitiveCollection<List<string>>("EventKinds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("event_kinds");

                    b.Property<DateTimeOffset?>("LastDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivered_at");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_failure_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_webhook_subscriptions_enabled");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("ix_webhook_subscriptions_engagement_id");

                    b.ToTable("webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredCampaignRecipient", b =>
                {
                    b.HasOne("Rod.Persistence.Configurations.StoredCampaign", "Campaign")
                        .WithMany("Recipients")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredImplantTaskNonce", b =>
                {
                    b.HasOne("Rod.CoreState.Implants.Implant", null)
                        .WithOne()
                        .HasForeignKey("Rod.Persistence.Configurations.StoredImplantTaskNonce", "ImplantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredOperatorApiToken", b =>
                {
                    b.HasOne("Rod.CoreState.Operators.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredOperatorCredential", b =>
                {
                    b.HasOne("Rod.CoreState.Operators.Operator", null)
                        .WithOne()
                        .HasForeignKey("Rod.Persistence.Configurations.StoredOperatorCredential", "OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rod.Persistence.Configurations.StoredCampaign", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
